### ISSUE TITLE
Which License?

### ISSUE THREAD

**Issue by renoth** [42Lines/wicket-source#15]
A missing license on this code is preventing my organization from using this plugin. Could you add a license to your project please?

**Comment by jennybrown8** [comment]
I forked the project when I changed employers some years back.  My fork is at https://github.com/jennybrown8/wicket-source/ and I've added the Apache License v2.0 there.  To the best of my understanding this matches the spirit in which it was developed originally and how I expect it to maintain it going forward.

**Comment by renoth** [comment]
Thank you!
