### ISSUE TITLE
Chrome extension pending approval of Chrome devtools experimental APIs

### ISSUE THREAD

**Issue by jennybrown8** [42Lines/wicket-source#3]
The Chrome extension is nearly ready but pending release of the devtools APIs out of experimental status.  Need to monitor and retest as APIs are approved.

**Comment by jennybrown8** [comment]
Chrome plugin is in the Downloads area.  Built for Chrome v18 which is currently in dev channel; but no longer uses experimental APIs.  So it should work when Chrome v18 reaches the Stable channel.

**Comment by martin-g** [comment]
How we can install this plugin ?
I don't find it in the web store and Chrome denies to install the .crx. Please update the Wiki with this information.

**Comment by jennybrown8** [comment]
It looks like Chrome changed their install policy.
http://support.google.com/chrome_webstore/bin/answer.py?hl=en&answer=2664769&p=crx_warning

It looks like you can download it and then open the Extensions page to
install it by hand.  It will no longer install directly from github.  I
will add wiki info on how to do this.

I will also look into adding this to the Chrome Web Store.  Thank you for
pointing out the problem!

**Comment by jennybrown8** [comment]
I've added it to the web store, and linked it from the Wiki.
https://chrome.google.com/webstore/search/WicketSource

**Comment by martin-g** [comment]
Just installed it and it works very well!
Thank you, Jenny!

**Comment by jennybrown8** [comment]
Great!
